/*
 * dotcom-monitor
 *
 * dotcom-monitor API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dotcommonitor

import (
	"context"
	"net/http"
	"reflect"
	"testing"
)

func TestTaskApiService_AddTask(t *testing.T) {
	type fields struct {
		client *APIClient
	}
	type args struct {
		ctx    context.Context
		device Task
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    Result
		want1   *http.Response
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &TaskApiService{
				client: tt.fields.client,
			}
			got, got1, err := a.AddTask(tt.args.ctx, tt.args.device)
			if (err != nil) != tt.wantErr {
				t.Errorf("TaskApiService.AddTask() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("TaskApiService.AddTask() got = %v, want %v", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("TaskApiService.AddTask() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func TestTaskApiService_DeleteTask(t *testing.T) {
	type fields struct {
		client *APIClient
	}
	type args struct {
		ctx    context.Context
		taskId string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    Result
		want1   *http.Response
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &TaskApiService{
				client: tt.fields.client,
			}
			got, got1, err := a.DeleteTask(tt.args.ctx, tt.args.taskId)
			if (err != nil) != tt.wantErr {
				t.Errorf("TaskApiService.DeleteTask() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("TaskApiService.DeleteTask() got = %v, want %v", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("TaskApiService.DeleteTask() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func TestTaskApiService_EditTask(t *testing.T) {
	type fields struct {
		client *APIClient
	}
	type args struct {
		ctx    context.Context
		taskId string
		task   Task
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    Result
		want1   *http.Response
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &TaskApiService{
				client: tt.fields.client,
			}
			got, got1, err := a.EditTask(tt.args.ctx, tt.args.taskId, tt.args.task)
			if (err != nil) != tt.wantErr {
				t.Errorf("TaskApiService.EditTask() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("TaskApiService.EditTask() got = %v, want %v", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("TaskApiService.EditTask() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func TestTaskApiService_GetTask(t *testing.T) {
	type fields struct {
		client *APIClient
	}
	type args struct {
		ctx    context.Context
		taskId string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    Task
		want1   *http.Response
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &TaskApiService{
				client: tt.fields.client,
			}
			got, got1, err := a.GetTask(tt.args.ctx, tt.args.taskId)
			if (err != nil) != tt.wantErr {
				t.Errorf("TaskApiService.GetTask() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("TaskApiService.GetTask() got = %v, want %v", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("TaskApiService.GetTask() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}

func TestTaskApiService_GetTasks(t *testing.T) {
	type fields struct {
		client *APIClient
	}
	type args struct {
		ctx      context.Context
		deviceId string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    []int32
		want1   *http.Response
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &TaskApiService{
				client: tt.fields.client,
			}
			got, got1, err := a.GetTasks(tt.args.ctx, tt.args.deviceId)
			if (err != nil) != tt.wantErr {
				t.Errorf("TaskApiService.GetTasks() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("TaskApiService.GetTasks() got = %v, want %v", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("TaskApiService.GetTasks() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}
