/*
 * dotcom-monitor
 *
 * dotcom-monitor API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dotcommonitor

import (
	"context"
	"net/http"
	"reflect"
	"testing"
)

func TestPlatformsApiService_GetPlataforms(t *testing.T) {
	type fields struct {
		client *APIClient
	}
	type args struct {
		ctx context.Context
	}

	tests := []struct {
		name    string
		fields  fields
		args    args
		want    []Platform
		want1   *http.Response
		wantErr bool
	}{
		{"NoConnectivity", fields{client: generateConfigFake()}, args{ctx: generateContextCanceled()}, nil, nil, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &PlatformsApiService{
				client: tt.fields.client,
			}
			got, got1, err := a.GetPlataforms(tt.args.ctx)
			if (err != nil) != tt.wantErr {
				t.Errorf("PlatformsApiService.GetPlataforms() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("PlatformsApiService.GetPlataforms() got = %v, want %v", got, tt.want)
			}
			if !reflect.DeepEqual(got1, tt.want1) {
				t.Errorf("PlatformsApiService.GetPlataforms() got1 = %v, want %v", got1, tt.want1)
			}
		})
	}
}
