/*
 * dotcom-monitor
 *
 * dotcom-monitor API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dotcommonitor

type AlertSilencePeriod struct {
	AlertSilenceMin int32 `json:"Alert_Silence_min,omitempty"`
}
