/*
 * dotcom-monitor
 *
 * dotcom-monitor API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dotcommonitor

type DeviceNotificationsNotificationGroups struct {
	Id           int32 `json:"Id,omitempty"`
	TimeShiftMin int32 `json:"Time_Shift_Min,omitempty"`
}
