/*
 * dotcom-monitor
 *
 * dotcom-monitor API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dotcommonitor

type TaskGetParams struct {
	Name  string `json:"Name,omitempty"`
	Value string `json:"Value,omitempty"`
}
