/*
 * dotcom-monitor
 *
 * dotcom-monitor API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dotcommonitor

type PlatformPackages struct {
	PackageId   int32  `json:"Package_Id,omitempty"`
	PackageName string `json:"Package_Name,omitempty"`
	PlatformId  int32  `json:"Platform_Id,omitempty"`
}
